### ISSUE TITLE
无法运行游戏，缺少音频文件

### ISSUE THREAD

**Issue by xulouzhe** [wavedeng/-#1]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "E:/Desktop/--master/my-golden-miner/Gold-Miner.py", line 34, in <module>
    sound = gamebox.load_sound("mining_music.wav")
  File "E:\Desktop\--master\my-golden-miner\gamebox.py", line 147, in load_sound
    _urlretrieve(url_or_filename, filename)
  File "C:\Users\Administrator\Anaconda3\envs\game\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Administrator\Anaconda3\envs\game\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\Anaconda3\envs\game\lib\urllib\request.py", line 510, in open
    req = Request(fullurl, data)
  File "C:\Users\Administrator\Anaconda3\envs\game\lib\urllib\request.py", line 328, in __init__
    self.full_url = url
  File "C:\Users\Administrator\Anaconda3\envs\game\lib\urllib\request.py", line 354, in full_url
    self._parse()
  File "C:\Users\Administrator\Anaconda3\envs\game\lib\urllib\request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'mining_music.wav'

Process finished with exit code 1

**Comment by daywithday** [comment]
34 35行前面加个 # 注释掉 或者目录下自己放个mp3  然后再 改下名字

**Comment by xulouzhe** [comment]
谢谢
